// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-SZYfWTyqufKjQk1RqPqpCWvW4zhJaM',
    appId: '1:368166668786:web:f6d40d62014fbc7291c36b',
    messagingSenderId: '368166668786',
    projectId: 'chat-app-52914',
    authDomain: 'chat-app-52914.firebaseapp.com',
    storageBucket: 'chat-app-52914.firebasestorage.app',
    measurementId: 'G-69N0NS6FBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj5qmKxZN40anWAwnEfR2gIcQXjnDZoB8',
    appId: '1:368166668786:android:a5040f1659c16c5991c36b',
    messagingSenderId: '368166668786',
    projectId: 'chat-app-52914',
    storageBucket: 'chat-app-52914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdI0JgHt8kGT9KT19vHAEgePRw6YPoMss',
    appId: '1:368166668786:ios:161edd362d7b845291c36b',
    messagingSenderId: '368166668786',
    projectId: 'chat-app-52914',
    storageBucket: 'chat-app-52914.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdI0JgHt8kGT9KT19vHAEgePRw6YPoMss',
    appId: '1:368166668786:ios:161edd362d7b845291c36b',
    messagingSenderId: '368166668786',
    projectId: 'chat-app-52914',
    storageBucket: 'chat-app-52914.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB-SZYfWTyqufKjQk1RqPqpCWvW4zhJaM',
    appId: '1:368166668786:web:45334a59b6e65f9391c36b',
    messagingSenderId: '368166668786',
    projectId: 'chat-app-52914',
    authDomain: 'chat-app-52914.firebaseapp.com',
    storageBucket: 'chat-app-52914.firebasestorage.app',
    measurementId: 'G-MDWXNFPXHC',
  );

}